Deprecate ap/chain disagreement. Standalone instances
nullpub/datum pull request #19
Opened 2021-03-24 19:49 UTC by SamProtas

Cherry-picked the content we discussed from the original PR here: https://github.com/nullpub/datum/pull/17

2021-03-26 16:28 UTC, baetheus approved these changes

2021-03-26 18:16 UTC, SamProtas commented on src/DatumEither.ts
> +export const sequenceTuple = sequenceT(Apply);
Looking through this PR again, this is breaking actually. Going to undo this and the below change and push this off until 4.0

2021-03-26 18:18 UTC, SamProtas commented
Balls in your court now. Let me know if there's anything else you'd like to see in this release. Otherwise I'll branch off and start the 4.0 as discussed.

2021-03-29 16:16 UTC, baetheus commented
I'll go over the changes on this asap and test it against some dependent projects asap. Thanks again!

2021-04-01 01:09 UTC, baetheus requested changes

2021-04-01 01:09 UTC, baetheus commented on package.json
> +  "version": "3.5.0",
Version numbers are managed with standard-version. If you don't mind, this could be reverted and on the subsequent release commit it will be bumped.

2021-04-01 04:17 UTC, baetheus commented
I'll use release-as to handle the version change

2021-04-01 04:18 UTC, merged